# Modified from the [Default TagBot template in PkgTemplates](https://github.com/JuliaCI/PkgTemplates.jl/blob/master/templates/github/workflows/TagBot.yml)
# Trigger TagBot only if
name: TagBot

on:
  repository_dispatch:
    types: [trigger-tagbot]
jobs:
  TagBot:
    # if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
          changelog: |
            ## {{ package }} {{ version }}
            ${{ github.event.head_commit.message }}
            {% if previous_release %}
            [Diff since {{ previous_release }}]({{ compare_url }})
            {% endif %}
            {% if custom %}
            {{ custom }}
            {% endif %}
            {% if issues %}
            **Closed issues:**
            {% for issue in issues %}
            - {{ issue.title }} (#{{ issue.number }})
            {% endfor %}
            {% endif %}
            {% if pulls %}
            **Merged pull requests:**
            {% for pull in pulls %}
            - {{ pull.title }} (#{{ pull.number }}) (@{{ pull.author.username }})
            {% endfor %}
            {% endif %}

          registry: okatsn/OkRegistry
